### UPDATE ACTOR
PUT http://localhost:3000/actors/25.json
Content-Type: application/json

{
  "first_name": "Mark"
}

### CREATE ACTOR
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Smith",
  "known_for": "This really good movie",
  "gender": "male",
  "age": "21"
}

### DELETE ACTOR
DELETE http://localhost:3000/actors/45.json

### UPDATE MOVIE
PUT http://localhost:3000/movies/7.json
Content-Type: application/json

{
  "english":
}

### CREATE MOVIE
POST http://localhost:3000/movies.json
Content-Type: application/json

{
  "title": "Air Bud",
  "year": "1999",
  "plot": "This really good movie about a great actor and his dog",
  "director": "Mavi",
  "english": "false"
}

### DELETE MOVIE
DELETE http://localhost:3000/movies/2

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Movie_genre create
POST http://localhost:3000/movie_genres.json
Content-Type: application/json

{
  "movie_id": 5,
  "genre_id": 1
}

